{{- range .Values.clusters }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "monitoring"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .destinationServer }}
  project: default
  source:
    chart: adwerx/awx
    repoURL: https://adwerx.github.io/charts
    targetRevision: {{ .apps.awx.version }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
