{{- range .Values.clusters }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "vault"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .destinationServer }}
  project: default
  source:
    path: .
    repoURL: https://github.com/hashicorp/vault-helm
    targetRevision: {{ .apps.vault.version }}
    helm:
      parameters:
      - name: server.dev.enabled
        value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
